apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources (same as in dev)
resources:
  - ../../../base/services  # Base configuration with global-values.yaml

helmCharts:
- name: bookinfo-service
  releaseName: bookinfo-service
  namespace: bookinfo-qa
  version: 1.0.4-rc1 # Updated with ConfigMap support for API standardization
  repo: https://muralikrishnagk.github.io/bookinfo-charts
  valuesFile: ../../../base/services/global-values.yaml
  additionalValuesFiles:
    - ../values.yaml # Global qa overlay values
    - bookinfo-service/values.yaml # Service-specific values

- name: bookinfo-processor
  releaseName: bookinfo-processor
  namespace: bookinfo-qa
  version: 0.1.4 # Updated with ConfigMap support for API standardization
  repo: https://muralikrishnagk.github.io/bookinfo-charts
  valuesFile: ../../../base/services/global-values.yaml
  additionalValuesFiles:
    - ../values.yaml # Global qa overlay values
    - bookinfo-processor/values.yaml # Service-specific values

