# QA values for bookinfo-service
replicaCount: 2

image:
  repository: localhost:5000/bookinfo-service
  tag: v1.0.3-rc1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  # port: 80 is inherited from the chart's default values.yaml

# ingress: # Ingress is handled by the separate infra component
#   enabled: false

resources:
  limits:
    cpu: "150m"
    memory: "192Mi"
  requests:
    cpu: "75m"
    memory: "96Mi"

env:
  - name: PORT
    value: "9090"
  # Add other qa-specific environment variables here

# ConfigMap settings for the service
configMap:
  enabled: true
  data:
    API_TIMEOUT: "5000"
    MAX_CONNECTIONS: "10"
    DB_POOL_SIZE: "3"
    LOG_LEVEL: "info"
    FEATURE_FLAGS: "reviews-enabled,ratings-enabled"
    SERVICE_ENV: "qa"
