# QA values for bookinfo-processor
replicaCount: 2

image:
  repository: localhost:5000/bookinfo-processor
  tag: 1.0.4-rc1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  # port: 80 is inherited from the chart's default values.yaml

# ingress: # Ingress is handled by the separate infra component
#   enabled: false

resources:
  limits:
    cpu: "150m"
    memory: "192Mi"
  requests:
    cpu: "75m"
    memory: "96Mi"

env:
  - name: PORT
    value: "9090"
  # Add other qa-specific environment variables here

# ConfigMap settings for the processor service
configMap:
  enabled: true
  data:
    PROCESSOR_MODE: "normal"
    MAX_THREADS: "4"
    CACHE_EXPIRY: "120"
    LOG_LEVEL: "info"
    PROCESSOR_ENV: "qa"
